elastic/ecs-logging-python

- .ci/Jenkinsfile
- .ci/scripts/lint.sh
- .ci/scripts/test.sh
- .gitignore
- noxfile.py
- pytest.ini
This is based on docker.
```
$ docker run --rm -ti -v $(pwd):/app -w /app python:3.7 .ci/scripts/test.sh 3.7
$ docker run --rm -ti -v $(pwd):/app -w /app python:3.7 .ci/scripts/lint.sh
```
> ci(jenkins): enable test and linting

- README.md
- ecs_logging/_stdlib.py
- ecs_logging/_structlog.py
- tests/test_stdlib_formatter.py
> Add support for Stdlib .log(..., extra={...})

- ecs_logging/_stdlib.py
- ecs_logging/_utils.py
- noxfile.py
- pyproject.toml
- tests/test_stdlib_formatter.py
This work started in https://github.com/elastic/ecs-logging-python/pull/10 by @comcast-jonm ([CLA signed here](https://github.com/elastic/ecs-logging-python/pull/10#issuecomment-626010145)). I've marked them as a co-author of the commit.
Adds the following features:
- `exclude_fields` which given a collection of dotted fields will exclude them since the `StdlibLogger` adds a lot of fields automatically.
- `stack_trace_limit` which mirrors the API for elastic-apm which changes the number of stack traces will be added to the `error.stack_trace` field.
- `process.*` fields are collected automatically
> Add exclude_fields and stack_trace_limit to StdlibLogger

- README.md
- ecs_logging/_stdlib.py
- pyproject.toml
- tests/test_apm.py
Grabs `elasticapm_span_id`, `elasticapm_transaction_id`, and `elasticapm_trace_id` from `LogRecord` which are automatically added by `elastic-apm` and places the values into ECS tracing fields `span.id`, `transaction.id`, and `trace.id` so logs can be correlated to spans and traces.
Closes #13
> Add support for Elastic APM log correlation

- ecs_logging/_utils.py
- tests/test_utils.py
> support lists

- README.md
Replaces references to version 1.5 with 1.6 as latest release implements
ecs version 1.6
> Update readme ecs version

- ecs_logging/_utils.py
- tests/test_apm.py
- tests/test_stdlib_formatter.py
- tests/test_structlog_formatter.py
- tests/test_utils.py
Relates to https://github.com/elastic/ecs-logging-python/issues/26
> Ensure @timestamp, log.level, and message fields are ordered per spec

- .gitignore
- docs/index.asciidoc
- docs/intro.asciidoc
- docs/setup.asciidoc
Will need to have the docs add these to elastic/docs as well.
Ref #26
> Add official docs

- .flake8
- tests/conftest.py
- tests/resources/spec.json
- tests/test_apm.py
- tests/test_stdlib_formatter.py
- tests/test_structlog_formatter.py
This adds validation against the upstream [spec](https://github.com/elastic/ecs-logging/blob/master/spec/spec.json).
Fixes #26
> Validate against spec

- ecs_logging/_stdlib.py
- tests/test_apm.py
As of 5.10.1, `elastic-apm` provides `service.name` as one of the log correlation fields. This PR supports that new addition.
> Add support for service.name

- ecs_logging/_stdlib.py
Will just be `${service.name}.log`, so pretty redundant but perhaps there will be a reason to have it configurable separate from `service.name` in the future? In any case, it's defined in the [spec](https://github.com/elastic/ecs-logging/blob/master/spec/spec.json#L75-L91).
> Pull in `event.dataset` for log correlation

- docs/setup.asciidoc
@bmorelli25 There's probably a better way to do this than with the full link. Especially because the full link points to `master`, not current, since current doesn't have it yet.
Closes https://github.com/elastic/apm-agent-python/issues/1007
> [DOCS] Add link to APM python `LOG_ECS_FORMATTING`

- tests/resources/spec.json
ECS logging specs automatic sync
> synchronize ecs-logging spec

- CHANGELOG.md
- ecs_logging/_structlog.py
- ecs_logging/_utils.py
- tests/conftest.py
- tests/test_apm.py
- tests/test_structlog_formatter.py
> Fix merging dicts for duplicate dotted keys

- .pre-commit-config.yaml
- CHANGELOG.md
- ecs_logging/_utils.py
- tests/test_structlog_formatter.py
> Add default/fallback behavior for json.dumps

- CHANGELOG.md
- ecs_logging/_stdlib.py
- tests/test_stdlib_formatter.py
Formatting of a message fails in the `StdlibFormatter` when the
`exc_info` parameter is `False`. The traceback shows that handling of
the boolean is not done correct in the formatting for error type and
message.
```python
Traceback (most recent call last):
File "lib/python3.8/logging/__init__.py", line 1081, in emit
msg = self.format(record)
File "lib/python3.8/logging/__init__.py", line 925, in format
return fmt.format(record)
File "ecs_logging/_stdlib.py", line 117, in format
result = self.format_to_ecs(record)
File "ecs_logging/_stdlib.py", line 163, in format_to_ecs
value = extractors[field](record)
File "ecs_logging/_stdlib.py", line 150, in <lambda>
if (r.exc_info is not None and r.exc_info[0] is not None)
TypeError: 'bool' object is not subscriptable
```
This replaces the lambda …
> Fix TypeError when exc_info=False

- .pre-commit-config.yaml
- ecs_logging/_stdlib.py
- mypy.ini
- noxfile.py
- tests/test_stdlib_formatter.py
> Match StdlibFormatter signature with logger.Formatter

- docs/intro.asciidoc
This adds a link to a new [Python ECS logging tutorial](https://www.elastic.co/guide/en/cloud/current/ec-getting-started-search-use-cases-python-logs.html) in the Cloud docs.
@bmorelli25, or anyone, please let me know if you think there might be a better place for this link.
Please see also https://github.com/elastic/ecs-logging-nodejs/pull/99
> Add a link to the Python ECS logging tutorial in the Cloud docs

- tests/test_apm.py
- tests/test_structlog_formatter.py
Fixes some test issues caused by upstream release 6.5.0 of the Python agent
> Remove .log from event.dataset

- .pre-commit-config.yaml
- ecs_logging/_stdlib.py
- pyproject.toml
> Fix type hint for _stdlib `style` arg

- .pre-commit-config.yaml
VSCode decided to reformat everything as well, sorry for so much whitespace noise.
> Switch flake8 to github (gitlab was failing in CI)

- pyproject.toml
The <3 requirement for flit_core is (seemingly) leftover from python2 support. This removes that requirement and some python2 leftovers.
Closes #93
> Allow flit_core 3.x and remove python2 leftovers

- CHANGELOG.md
- ecs_logging/_stdlib.py
- tests/conftest.py
- tests/test_apm.py
structlog doesn't need any changes, just a test change.
These tests won't go green until a new version of the python agent is released. Still a chicken and egg problem we haven't resolved. I tested locally with the following:
```
pip install https://github.com/basepi/apm-agent-python/archive/refs/heads/service_environment.zip
```
Ref https://github.com/elastic/apm-agent-python/issues/1772
Depends on https://github.com/elastic/apm-agent-python/pull/1833
> Add service.environment to stdlib formatter

- CHANGELOG.md
- ecs_logging/_structlog.py
- tests/test_structlog_formatter.py
When using the StructlogFormatter, logs with exceptions (e.g. produced by using `logger.exception(...)`) currently result in a `exception` key at the root of the log, which is not a valid ECS field. It should be in the [`error.stack_trace` field](https://www.elastic.co/guide/en/ecs/current/ecs-error.html#field-error-stack-trace) instead. 
This PR addresses a small part of the [disparity between the StructlogFormatter and the StdlibFormatter ](https://github.com/elastic/ecs-logging-python/issues/73). Until that is addressed in it's entirety, this patch will help users of this package (like myself) to output logs that comply with the ECS specification.
> Move exception stack trace to ECS-compliant field for StructlogFormatter

- tests/conftest.py
- tests/test_stdlib_formatter.py
Repeat of #100 because CI in order to fix CI issues.
* Remove unused imports
* Undefined name index
> Small fixes

- .github/dependabot.yml
no requirements.txt file hence no need to use pip
> dependabot: remove pip

- ecs_logging/__init__.py
- ecs_logging/_structlog.py
Version 3.12 of python deprecated the utcfromtimestamp, this PR uses the correct method.
> fix: use fromtimestamp instead of deprecated utcfromtimestamp

- .github/labeler-config.yml
- .github/workflows/labeler.yml
Use the same config as in apm agent python: consider everyone from elastic as internal and stop adding issues to the old board.
> ci: fix issue labeler

- README.md
- docs/setup.asciidoc
Relates to https://github.com/elastic/docs/pull/2994
This PR updates some links in the [ECS Logging Python Reference](https://www.elastic.co/guide/en/ecs-logging/python/current/index.html) to use shared attributes for some documentation links, so that they stay up-to-date.
> Generalize documentation links

- .github/workflows/periodic.yml
- .github/workflows/test-docs.yml
- .github/workflows/test.yml
- ecs_logging/_stdlib.py
- ecs_logging/_structlog.py
- noxfile.py
- pyproject.toml
- tests/test_apm.py
- tests/test_stdlib_formatter.py
- tests/test_structlog_formatter.py
While at it test on modern python versions.
Closes #88
> Don't de-dot ecs.version

- .github/workflows/test.yml
- ecs_logging/_stdlib.py
- ecs_logging/_structlog.py
- ecs_logging/_utils.py
Move from comments to Python 3 type annotations. While at it cleanup also imports.
Fix #79
> Rewrite type annotations

- .github/workflows/periodic.yml
- .github/workflows/test-docs.yml
- .github/workflows/test.yml
- noxfile.py
- pyproject.toml
- tests/test_stdlib_formatter.py
Bump to Python 3.8 as baseline and add 3.13 support. We have to drop 3.7 testing because it's not available anymore with github setup python action.
> Bump baseline supported version to Python 3.8

- docs/docset.yml
- docs/reference/index.md
- docs/reference/installation.md
Follow up to https://github.com/elastic/ecs-logging-python/pull/157
When using cross-repo links, the path should be relative to the `docset.yml` not the full path within the repo ([updated docs-builder docs](https://elastic.github.io/docs-builder/syntax/links/#cross-repository-links)).
> [docs] Clean up cross-repo links

- docs/reference/installation.md
Fix external links that incorrectly use `.md` instead of `.html`.
> [docs] Fix external links

- .pre-commit-config.yaml
- ecs_logging/_stdlib.py
This commit fixes a typo observed in
https://github.com/elastic/ecs-logging-python/pull/172#discussion_r2166707106
Also allows to simply the code without a need for a helper function.
> Fix typo identified in #172
